### ISSUE TITLE
Fast 5359 - KPN Box 12 - Request timing out

### ISSUE THREAD

**Issue by CasperPennings** [iMicknl/ha-sagemcom-fast#115]
I tried connecting my KPN Box 12 using the latest version and the settings provided here but only get a timeout after a while.
<img width="455" alt="image" src="https://github.com/iMicknl/ha-sagemcom-fast/assets/152322874/5ab0b9ed-f40b-475d-9a7c-4d19959c8b70">

**Comment by CasperPennings** [comment]
In the screenshot MD5 is selected but I used SHA512

**Comment by bakonyiferenc** [comment]
Please unselect "Uses an SSL certificate" if your KPN Box 12 is accessible via http://mijnmodem.kpn/ (instead of https://mijnmodem.kpn/)

**Comment by CasperPennings** [comment]
Thank you for your suggestion but unfortunately that also doesn't work, it results in an "Unexpected error". I've double checked if the password is correct and it is. Is there any way I can get a more detailed error report?

**Comment by bakonyiferenc** [comment]
To get more details about the error [enable debug logging](https://github.com/iMicknl/ha-sagemcom-fast?tab=readme-ov-file#enable-debug-logging) and check HA logs.

**Comment by CasperPennings** [comment]
`Traceback (most recent call last):
  File "/config/custom_components/sagemcom_fast/config_flow.py", line 87, in async_step_user
    return await self.async_validate_input(user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sagemcom_fast/config_flow.py", line 69, in async_validate_input
    await client.login()
  File "/usr/local/lib/python3.11/site-packages/sagemcom_api/client.py", line 271, in login
    response = await self.__api_request_async([actions], True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sagemcom_api/client.py", line 201, in __api_request_async
    raise UnknownException(result)
sagemcom_api.exceptions.UnknownException`

**Comment by bakonyiferenc** [comment]
The most interesting part is logged after the traceback like
`sagemcom_api.exceptions.UnknownException: <!doctype html
>
<html lang=en>
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you
 entered the URL manually please check your spelling and
 try again.</p>`

**Comment by CasperPennings** [comment]
Well there isn't anything there as far I can see 😅. I've included the log file 
[home-assistant_2024-03-22T09-13-57.816Z.log](https://github.com/iMicknl/ha-sagemcom-fast/files/14720303/home-assistant_2024-03-22T09-13-57.816Z.log)

**Comment by CasperPennings** [comment]
Seems like it happens when the response to the post is not 200
```if response.status != 200:
                result = await response.text()
                raise UnknownException(result)```

**Comment by bakonyiferenc** [comment]
Oh, perhaps you need to adjust the loglevel of HA to get the details of UnknownException:
```yaml
logger:
  default: warning
  logs:
    custom_components.sagemcom_fast: debug
```

**Comment by iMicknl** [comment]
My own Sagemcom router (Ziggo) is in bridge mode; thus it is hard for me to work on this integration and underlying library. This integration + library is still very simple and does need better error logging / handling for sure. 

@CasperPennings what is your router model and firmware version? A month ago I tested this integration with a new KPN modem

**Comment by CasperPennings** [comment]
"Manufacturer": "Sagemcom",
        "ManufacturerOUI": "34495B",
        "ModelName": "SagemcomFast5359_KPN",
        "Description": "SagemcomFast5359_KPN Sagemcom NL",
        "ProductClass": "F5359s",
        "SerialNumber": "LK21345ME551512",
        "HardwareVersion": "1.0",
        "SoftwareVersion": "V12.C.23.15.06",

**Comment by Starf0x** [comment]
It has to do with the new Firmware that KPN installed is it rather new and different, so this integration will not work anymore.

**Comment by NLCas8** [comment]
I got the same hardware and software versions as posted above and I'm running into a similar issue:
`Failed to connect, please try again`


> It has to do with the new Firmware that KPN installed is it rather new and different, so this integration will not work anymore.

@Starf0x  Did you find out what changed in the new KPN firmware that causes the integration to fail on setup?
