### ISSUE TITLE
Support for FAST3686

### ISSUE THREAD

**Issue by Hount** [iMicknl/ha-sagemcom-fast#124]
Hi, I can provide additional information if needed.

Standard Specification Compliant	EuroDOCSIS 3.0
Hardware Version	V2.0
Software Version	[my-ips-specific]_3.591.0
Model Name	FAST3686
Linux S/W Version	2.6.30-1.7.1mp3-svn19302

**Comment by MaaGik2** [comment]
Hi, I need to for mine plz !

Model Name F@st3686 V1B
Standard Specification Compliant EuroDOCSIS 3.0
SFR-PC20_3.680.0-T1

Ty!

**Comment by Hount** [comment]
Still relevant.

**Comment by iMicknl** [comment]
@Hount what is the error you get? Unfortunately, in most cases, this means that your device uses a different API and thus is not supported.

**Comment by Hount** [comment]
> @Hount what is the error you get? Unfortunately, in most cases, this means that your device uses a different API and thus is not supported.

"Failed to connect, please try again"
when adding the integration after installing 0.33 with HACS

I could not find more detailed info / logs yeat.

**Comment by Hount** [comment]
And quick connectivity tests
* I can ping modem from HA
* I can curl modem's login page from HA
* I've tested both http://ip and plain ip as host in Sagemcom integration "Host" -field
* username/ password are correct
* I tested both MD5 and SHA512 encryption methods
* SSL and it's verify should not be required as the modem's web ui does not use such?
