### ISSUE TITLE
Error fetching sagemcom_hosts data: Error communicating with API: list index out of range

### ISSUE THREAD

**Issue by iMicknl** [iMicknl/ha-sagemcom-fast#13]
## Versions

| Key                               | Value |
|-----------------------------------|-------|
| Home Assistant version            |  latest dev     |
| Integration version               |  0.2.1     |
| Sagemcom F@st model               |  Sagemcom FAST3890     |
| Sagemcom F@st firmware (optional) |  FAST3890V3_DELTA-SIP_sw05.76.9.7k-3     |

## Describe the bug

It seems that the DataUpdateCoordinator only works after startup, and afterwards it will give an error regarding the list index out of range.

## Expected behavior

Every 10 seconds pull the active devices and merge the lists, without throwing errors.

## Additional context

```
2021-04-09 19:36:36 ERROR (MainThread) [custom_components.sagemcom_fast] Error fetching sagemcom_hosts data: Error communicating with API: list index out of range
```

[bug]

**Comment by arunpoudel** [comment]
Looks like there is no list operation in the function where the error is being logged.

What version of sagemcom_api are you using?

**Comment by iMicknl** [comment]
`sagemcom_api===1.0.4`, but this only did happen once during development. Just logged it here to see if it happens more often.
