### ISSUE TITLE
Sagemcom F3896LG

### ISSUE THREAD

**Issue by janwillemnell** [iMicknl/ha-sagemcom-fast#133]
It seems our provider (ziggo) has a Saemcom F3896LG, which does not work under the F3896 as shown in the table. Probably it needs to be added. I am also not able to login (same as the people in the thread below). 

https://community.home-assistant.io/t/ziggo-modem-new-model-sagemcom-f3896lg/689883

**Comment by iMicknl** [comment]
@janwillemnell what is the error you get? Are you able to check the requests on your Ziggo modem login page?
