### ISSUE TITLE
[Device Tracker] After reboot, not connected devices have status 'unavailable'

### ISSUE THREAD

**Issue by iMicknl** [iMicknl/ha-sagemcom-fast#14]
## Versions

| Key                               | Value |
|-----------------------------------|-------|
| Home Assistant version            |  latest dev     |
| Integration version               |  0.2.1     |
| Sagemcom F@st model               |  Sagemcom FAST3890     |
| Sagemcom F@st firmware (optional) |  FAST3890V3_DELTA-SIP_sw05.76.9.7k-3     |
## Describe the bug

After a reboot of Home Assistant, devices that are not connected but which have been connected in the past, will show as unavailable.

<img width="903" alt="Screen Shot 2021-04-11 at 16 50 35" src="https://user-images.githubusercontent.com/1424596/114309112-6013d480-9ae6-11eb-9e1b-dd2f2db44f05.png">

## To Reproduce

1. Connect device to network
2. Disconnect device from network
3. Reboot Home Assistant
4. Device will show as unavailable

## Expected behavior

Device will be home or not home.

## Additional context

We could see if we pull all devices, instead of only active. But this will clutter the entity registry a lot.
```
                hosts = await self._client.get_hosts(only_active=True)
```

Otherwise, we could loop through the entities on boot and add them to the list / dictionary. This is what other integration do.

[bug]

**Comment by arunpoudel** [comment]
I can take it if you don't want to take it.

**Comment by iMicknl** [comment]
@arunpoudel if you have time, go for it! My bandwidth is limited these weeks and there are quite some open issues on the Somfy integration to fix.

**Comment by djfanatix** [comment]
Hi, any update. I still have this issue with a BBOX3

thanks anyway!

**Comment by iMicknl** [comment]
@djfanatix  could you give https://github.com/arunpoudel/ha-sagemcom-fast/archive/refs/heads/master.zip a try? Extract this file and place `custom_components/sagemcom_fast` in your `custom_components` folder.

**Comment by djfanatix** [comment]
@iMicknl Thanks for the reply, but still the same after reloading or rebooting HA

**Comment by djfanatix** [comment]
@iMicknl After testing for a few days, it notice that after a reboot, everybody stays on 'away', so that's also not good

**Comment by djfanatix** [comment]
Do you have an idea how to fix this issue? with the latest update everybody stays on away.
But in the logs it seems that the integration is polling the router successful.
When removing the plugin and reinstalling, the device list and presence is correct

**Comment by djfanatix** [comment]
I just checked with the latest version, but still the same.
New entitities are also not created.

**Comment by iMicknl** [comment]
If it would have been fixed, it would have been mentioned in the changelog and this issue would have been closed. 😉

However, I just released a small maintenance update where all dependencies where updated, nothing more. I don't have time to work on this integration at the moment, thus others would need to tackle this..
