### ISSUE TITLE
Device Tracking Inconsistent

### ISSUE THREAD

**Issue by BenHornerTech** [iMicknl/ha-sagemcom-fast#15]
## Versions

| Key                               | Value |
|-----------------------------------|-------|
| Home Assistant version            |2021.4.6|
| Integration version               |0.2.2|
| Sagemcom F@st model               |5364|
| Sagemcom F@st firmware (optional) |SG4K10002816t|

## Describe the bug

Presence keeps jumping from home to away and back again sporadically every few minutes

## To Reproduce

1. Go to device.tracker.my_iphone
2. Status is flipping from Home to Away constantly even when I am at home and not moving away from my house

## Expected behavior

Device should only switch to home when it is no longer connected to WiFi

## Screenshot

<img width="471" alt="Screenshot 2021-04-21 at 14 03 55" src="https://user-images.githubusercontent.com/7114638/115558226-6eae7880-a2aa-11eb-96ef-9c042d5120d6.png">

## Additional context

Additional consideration is that I am using a mesh network for WiFi separate to my Sagemcom router, though the router would still have my mac address for the device present on the system and it does show when I log into the router GUI

[bug]

**Comment by iMicknl** [comment]
Thanks for reporting, @BenHornerTech! Could you check if you have multiple entries for the same phone? 

Are you using the WiFi network of the Sagemcom as well, or only the mesh network? I wonder if there are different entities for the ethernet and wifi connection, even though they share the same mac address.

**Comment by BenHornerTech** [comment]
Looks like just single entries both on my Sagecom router GUI and via Home Assistant.  This is also true of my wife's phone, though they don't move between home and away at the same time.

I'm only using the mesh WiFi and have disabled the WiFi on my Sagecom router.  All my connections on the Sagecom show in the Wired connections section.

**Comment by iMicknl** [comment]
@arunpoudel would you have any idea? I am not sure why this could happen.

**Comment by arunpoudel** [comment]
Some devices turn off wifi periodically for power saving, maybe that is the reason? But this is too frequent for that. 

Another reason might be that the mesh setup, but I cannot be certain of that either. 

Does your wife also have the same model of phone?

**Comment by BenHornerTech** [comment]
Yes, she also has an iPhone, though looking at various devices on the network and their presence (such as LIFX bulbs or Alexa) they too can drop in and out across the day.  Usually the drop outs are brief and show as being away for 30 seconds, which also matches my scan interval for the integration.

**Comment by BenHornerTech** [comment]
I've had a thought that may provide a workable solution to the problem, as I am only looking at this tool to provide me with immediate notifications when certain devices join my network, such as guests arriving at my house.

Would it be possible to only set the entity to 'Away' if the Sagemcom device entry has not been seen in the last 2 or 3 polls rather than as soon as it's not seen?  This way, if the device isn't there for just one poll, but returns 30 seconds later, I don't end up getting 'Away' and 'Home' again notifications.  As the polling interval is customisable, maybe the number of polls before the entity is set to 'Away' could also be customisable.  Hopefully then, I get a notification when the device first arrives immediately, but have to (at most) wait to have an 'Away' notification 30 seconds after the device has left my wifi.

Does that sound like a workable solution?
