### ISSUE TITLE
Sagemcom F@st 5688b

### ISSUE THREAD

**Issue by Moha-maison** [iMicknl/ha-sagemcom-fast#157]
bonjour,

est ce que je peux avoir de l'aide pour connecter ma box fibre Sagemcom F@st 5688b, lors de la connection j'ai une erreur "Failed to connect, please try again"

Merci d'avance

Mohamed B.

**Comment by iMicknl** [comment]
Please communicate in English (you can use a translate tool if this helps). Can you access the ip address in your browser? Are you sure your Home Assistant can access this IP address?

**Comment by Moha-maison** [comment]
Hi,

Yes I can access the IP address, but on my browser I am automatically redirected to this address https://mabbox.bytel.fr/, but even with this address I can't connect, is there any information I can send to you to help me?

Thx for your help. 

Moha
