### ISSUE TITLE
Sagemcom F@st 5657

### ISSUE THREAD

**Issue by aleixsb** [iMicknl/ha-sagemcom-fast#16]
Hey!

Thanks for creating this integration! Really helpful.

I have the Sagemcom F@st 5657 and it's working as well with your plugin so you can add this to the list!

Best regards,

**Comment by aleixsb** [comment]
User: 1234
Password: 1234
Encryption: md5

**Comment by iMicknl** [comment]
Thanks for reporting, I will add it to the list! Did you receive your router with any specific provider?
(and is user and password always set to 1234, or could you change it?)

**Comment by aleixsb** [comment]
Hey!

This router is delivered by Masmovil and Pepephone is Spain.

1234:1234 is de default guest user with this model, at least for
Pepephone/Masmovil.
Admin user is set random for each device.
