### ISSUE TITLE
make available for Ziggo Sagemcom F3896LG-ZG

### ISSUE THREAD

**Issue by FransHalsjes** [iMicknl/ha-sagemcom-fast#166]
Add support for the new Ziggo modem (F3896LG-ZG)
Problem arises in connecting that the integration requires a user name, but that is not provided in the modem. There just the password is available to enter.

**Comment by iMicknl** [comment]
This modem is unfortunately using another API and not supported in this integration.

See https://github.com/iMicknl/python-sagemcom-api/issues/361 for more details.
