### ISSUE TITLE
Android MotoG9 discovery issue

### ISSUE THREAD

**Issue by cingolo** [iMicknl/ha-sagemcom-fast#2]
Environment:
Sagemcom F@st 3865bProximus (b-box3)
Release: 8c.514A
GUI Version
7.4.2.0

The  Sagemcom  Client seems to have issues while discovering my Androids devices. 
After further investigation the issue seems triggered by the 'hostname' and device type values seen into the router. By default in the router you don't have a friendly name so not sure if your application is expecting a value because in the HA entity you are mapping the same friendly name value.

Workaround is: change the device type from 'Generic' to 'Mobile phone' and assign a friendly name then reload the application 

Action Taken:

1) Added the Sagemcom client integration

2) Reloaded home Assistant

3) the client doesn't discover the Motorola G9 Android
Sagemcom F@st
192.168.1.1
12 devices and 12 entities

4) Tried to reload either the application or HA but no luck

5) Changed the Motorola device type and the friendly name in the router

6) Reloaded the client and issue is fixed

Apologies but i cannot share the logs somehow HA didn't print any logs even though i added the required lines in the configuration file.

**Comment by iMicknl** [comment]
Currently there not much is logged from the integration, thus you won't see a lot indeed.

Currently we use the following definition for the name, so that shouldn't be the issue. Are you familiar with Python and are you able to try if it works with the Python client directly? (https://github.com/iMicknl/python-sagemcom-api)

```python
    @property
    def name(self):
        """Return name of the device."""
        return self.user_host_name or self.host_name
```

**Comment by cingolo** [comment]
Ok i will give it a try by using the client.

**Comment by iMicknl** [comment]
@cingolo could you have a look if it works with the latest version? :)

**Comment by cingolo** [comment]
Oki, I will run few tests later today

Inviato da Yahoo Mail su Android 
 
  Il ven, 9 apr, 2021 alle 14:57, Mick ***@***.***> ha scritto:   


@cingolo could you have a look if it works with the latest version? :)
