### ISSUE TITLE
Unable to find the integration

### ISSUE THREAD

**Issue by pippo73** [iMicknl/ha-sagemcom-fast#22]
## Versions

| Key                               | Value |
|-----------------------------------|-------|
| Home Assistant version            |   2021.5.0    |
| Integration version               |   0.2.2    |
| Sagemcom F@st model               |   XGSR1644  (fibre x6)  |
| Sagemcom F@st firmware (optional) |   SGEk10001A05    |

## Describe the bug

I've installed the repository via HACS but I cannot find the integration

## To Reproduce

1. Install the repository in HACS (the files are present in _./config/custom_components/sagemcom_fast_ )
2. go in config - integratios - press the + button
3. serch for the sagem integration but it is not present :-(

## Expected behavior

I expect to find the sagem integration

## Screenshots

![2021-05-07 08_18_28-Configuration - Home Assistant e altre 6 pagine - Personale - Microsoft​ Edge](https://user-images.githubusercontent.com/757121/117408083-b6223f00-af0f-11eb-9077-1ebc0e04199a.png)

## Additional context

[bug]

**Comment by iMicknl** [comment]
Have you tried restarting HA, removing your browser cache and/or trying to access your instance in private mode?

I have seen this problem more often in HA, but this is not related to this integration unfortunately..

**Comment by pippo73** [comment]
Seems it was a chace problem. Now it works. thank you
