### ISSUE TITLE
Couldn't Log in

### ISSUE THREAD

**Issue by Allbruce** [iMicknl/ha-sagemcom-fast#23]
Hi

Thx for the effort to make this integration!
I'm new into home assistant and I have troubles to make it work.

I tried different things but I still get errors.

Is it possible to give an example of the credentials of the integration?
![Foto 28-05-2021 om 20 26](https://user-images.githubusercontent.com/79608545/120027237-68bb5e00-bff3-11eb-8add-c8f9a6a94697.jpg)

Thx in advance!

**Comment by iMicknl** [comment]
Which Sagemcom F@st router do you have? And how do you log in to the control panel?

In my example, I login to 192.168.11.1 and use a username and password provided by my ISP.

**Comment by Allbruce** [comment]
Thx for your quick response!

It’s a sagemcom of Proximus but I don’t find the exact number…When I use the host of my modem, the username en password witch I use to login by the website, I get an unexpected error.

**Comment by iMicknl** [comment]
Have you checked your log for any errors? An unexpected error should be visible in the log.

Please note that this integration only supports Sagemcom F@st routers.

**Comment by Allbruce** [comment]
﻿Is there a way to see witch type sagemcom it is?

I got this in the log:

[cid:C202D256-5114-4519-9150-CC2BED13A2FA-L0-001]




Op 29 mei 2021 om 01:16 heeft Mick Vleeshouwer ***@***.***> het volgende geschreven:

﻿

Have you checked your log for any errors? An unexpected error should be visible in the log.

Please note that this integration only supports Sagemcom ***@***.*** routers.

**Comment by Allbruce** [comment]
Is there a way to see witch type sagemcom it is?

I got this in the log:

![89BCB690-52C9-4D6B-A219-7F3514A31FF2](https://user-images.githubusercontent.com/79608545/120060605-f2e9dd80-c058-11eb-8762-62d9dd36f6ce.jpeg)

**Comment by iMicknl** [comment]
@Allbruce unfortunately, it seems that your device is not supported by this integration.
