### ISSUE TITLE
Is it possible to pull uptime information from the router to the home assistant ?

### ISSUE THREAD

**Issue by cvjensen** [iMicknl/ha-sagemcom-fast#24]
I would very much like to get uptime information from the router into home assistant so that I can compare if there has been power outage - is this possible?

**Comment by iMicknl** [comment]
What kind of information are you looking for? Does this describe what you are looking for: https://github.com/iMicknl/ha-sagemcom-fast/issues/7. 

Currently I have limited time to work on this project, but I will leave your feature request open if someone wants to contribute.

**Comment by cvjensen** [comment]
Yes that actually describes pretty well what I'm looking for . Has anyone tried to find a solution ?

**Comment by iMicknl** [comment]
Tracked with #7
