### ISSUE TITLE
Device has no mac address

### ISSUE THREAD

**Issue by djfanatix** [iMicknl/ha-sagemcom-fast#25]
## Versions

| Key                               | Value |
|-----------------------------------|-------|
| Home Assistant version       2021.8.8     |       |
| Integration version               |       |
| Sagemcom F@st model      Bbox3         |       |
| Sagemcom F@st firmware (optional) |       |

## Describe the bug
Deze fout is ontstaan door een aangepaste integratie.

```
Logger: homeassistant.components.device_tracker
Source: custom_components/nieuwe/device_tracker.py:35 
Integration: Apparaattracker 
First occurred: 7:22:38 (4 occurrences) 
Last logged: 7:26:29

Error while setting up sagemcom_fast platform for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/nieuwe/device_tracker.py", line 35, in async_setup_entry
    for idx, device in coordinator.data.items()
AttributeError: 'NoneType' object has no attribute 'items'
```
+

Deze fout is ontstaan door een aangepaste integratie.
```
Logger: custom_components.nieuwe
Source: helpers/update_coordinator.py:219 
Integration: nieuwe 
First occurred: 7:22:35 (4 occurrences) 
Last logged: 7:26:29

Error fetching sagemcom_hosts data: Error communicating with API: 'Device' object has no attribute 'mac_address'
```

## To Reproduce

Restart the integration

## Expected behavior

Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by iMicknl** [comment]
Let's first tackle your most recent issue.
