### ISSUE TITLE
[Fast 5655v2] Config Flow fails on keyError: 'id'

### ISSUE THREAD

**Issue by peter6863** [iMicknl/ha-sagemcom-fast#29]
## Versions

| Key                               | Value |
|-----------------------------------|-------|
| Home Assistant version            |   core-2021.11.1    |
| Integration version               |  latest available     |
| Sagemcom F@st model               |  5655v2     |
| Sagemcom F@st firmware (optional) |   HW ver 1.0; SW ver SG3G10000636; GUI ver 1.110.62; 

## Describe the bug

This error originated from a custom integration.

Logger: custom_components.sagemcom_fast
Source: custom_components/sagemcom_fast/__init__.py:60
Integration: Sagemcom F@st (documentation, issues)
First occurred: 21:06:31 (1 occurrences)
Last logged: 21:06:31

'id'
Traceback (most recent call last):
  File "/config/custom_components/sagemcom_fast/__init__.py", line 60, in async_setup_entry
    await client.login()
  File "/usr/local/lib/python3.9/site-packages/sagemcom_api/client.py", line 273, in login
    if data["id"] is not None and data["nonce"] is not None:
KeyError: 'id'

[bug]

**Comment by iMicknl** [comment]
Unfortunately I have not a lot of time lately to work on this integration and it is hard to debug issues when you don't have the hardware around. Do you perhaps have any Python / coding knowledge?
