### ISSUE TITLE
Sagecom F@st 3890V3 - {'code': 16777224, 'description': 'XMO_LOGIN_RETRY_ERR'}

### ISSUE THREAD

**Issue by done7k** [iMicknl/ha-sagemcom-fast#32]
## Versions

| Key                               | Value |
|-----------------------------------|-------|
| Home Assistant version            |    2021.12.5   |
| Integration version               |   "0.2.1"    |
| Sagemcom F@st model               |   3890V3    |
| Sagemcom F@st firmware (optional) |   FAST3890V3_MAGYAR_sw18.76.10.13c-1    |
|GUI ver              | 5.14.0 |

## Describe the bug

Performed Manual installation.
Attempted to add an integration with authentication method 'md5' as described in Table of supported devices but it failed to login. Then changed to 'sha512' and it succeeded . but on the integration card I see an error ‘Failed to set up. See log’. This is the log entry (only one):

`This error originated from a custom integration.

Logger: custom_components.sagemcom_fast
Source: custom_components/sagemcom_fast/__init__.py:60
Integration: Sagemcom F@st (documentation, issues)
First occurred: 9:13:08 PM (1 occurrences)
Last logged: 9:13:08 PM

{'code': 16777224, 'description': 'XMO_LOGIN_RETRY_ERR'}
Traceback (most recent call last):
  File "/config/custom_components/sagemcom_fast/__init__.py", line 60, in async_setup_entry
    await client.login()
  File "/usr/local/lib/python3.9/site-packages/sagemcom_api/client.py", line 265, in login
    response = await self.__api_request_async([actions], True)
  File "/usr/local/lib/python3.9/site-packages/sagemcom_api/client.py", line 235, in __api_request_async
    raise UnknownException(action_error)
sagemcom_api.exceptions.UnknownException: {'code': 16777224, 'description': 'XMO_LOGIN_RETRY_ERR'}
`
I can play with coding a bit but had an issue while installing your package from pypi on Ububntu. 20

`pip install sagecom_api

ERROR: Could not find a version that satisfies the requirement sagecom_api (from versions: none)
ERROR: No matching distribution found for `sagecom_api`
`
have python 3.8.10

## Expected behavior

Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by iMicknl** [comment]
Thanks for reporting! Currently I don't have much time to spend on this, due to other projects, however it is good to track this here.

>`pip install sagemcom_api

> ERROR: Could not find a version that satisfies the requirement sagecom_api (from versions: none)
> ERROR: No matching distribution found for sagecom_api

Looking at the error, are you sure you typed it correctly? It should be `pip install sagemcom_api`.

**Comment by done7k** [comment]
OMG... right! sagemcom_api.. got it.. will try to python it.. any short code example to start?

**Comment by done7k** [comment]
Managed to connect to my routed with sha512 hash only from a python script. With md5 it gives the error 'XMO_LOGIN_RETRY_ERR'. Deleted integration and added it again with sha512 hash. Now it is ok!  Not sure how it added with md5 before..
I noticed the  integration does not create any sensor for router but device_trackers for hosts only. Perhaps this is for 'feature request' but would be good to expose 'router':'home'|'unavailable' or 'wan0': 'down'. HA could try to reset power switch for router via zigbee or something.. Can not find proper XPATH url to get status of wan0.. Can you advice?

**Comment by iMicknl** [comment]
@done7k can I close this issue, and could you perhaps create a new one for your future request? (if there is no other open).

Currently I am not spending much time on this integration, however this would be more visible for other potential contributors.
