### ISSUE TITLE
Dublicate entities created

### ISSUE THREAD

**Issue by done7k** [iMicknl/ha-sagemcom-fast#33]
## Versions

| Key                               | Value |
|-----------------------------------|-------|
| Home Assistant version            |    2021.12.5   |
| Integration version               |   "0.2.1"    |
| Sagemcom F@st model               |   3890V3    |
| Sagemcom F@st firmware (optional) |   FAST3890V3_MAGYAR_sw18.76.10.13c-1    |
|GUI ver              | 5.14.0 |

## Describe the bug
I am not exactly sure what made it happen. But I noticed the integration gets stuck, setting all device_tracker entries 'Unavailable' status. in such a case I attempted to run 'Reload' option.  this all happened a few times. But now I found some entries duplicated with name ended '_2' .. when the original entity is 'Unavailable' and the second one seems gets actual status 'home'. 

## Expected behavior

Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by iMicknl** [comment]
Thanks for reporting, @done7k! I am not sure what happened here, but for sure, the code could be improved.

For now, I would advise to remove the config entry and than create a new config entry. Did you have an error in your log, because you had to reload the integration?

**Comment by done7k** [comment]
@iMicknl , you probably can close this issue. I have clarified this some time ago and did not make any update here. the root cause is some of my devices had no static IP address set. in this case the router reports the same device name twice or ever three times.. That is it.

**Comment by iMicknl** [comment]
@done7k however the mac address should be the same. I will double check if the macaddress is set as the unique identifier!

Thanks for checking! I will close this for now, but feel free to create a new one / reopen if you face it again.
