### ISSUE TITLE
[Proximus B-box] Config Flow fails on keyError: 'id'

### ISSUE THREAD

**Issue by djfanatix** [iMicknl/ha-sagemcom-fast#36]
## Versions

| Key                               | Value |
|-----------------------------------|-------|
| Home Assistant version       |  latest
| Integration version              | latest 1.2.5
| Sagemcom F@st model       |        bbox proximus
| Sagemcom F@st firmware (optional) |       |

## Describe the bug
Integration crashes on startup, see logfile below

## Screenshots

'id'
Traceback (most recent call last):
  File "/config/custom_components/sagemcom_fast/config_flow.py", line 86, in async_step_user
    return await self.async_validate_input(user_input)
  File "/config/custom_components/sagemcom_fast/config_flow.py", line 69, in async_validate_input
    await client.login()
  File "/usr/local/lib/python3.9/site-packages/sagemcom_api/client.py", line 278, in login
    if data["id"] is not None and data["nonce"] is not None:
KeyError: 'id'

## Additional context

[bug]

**Comment by iMicknl** [comment]
Have you ever been able to set up this integration? Since this is not an issue on start-up, but while trying to set up in your config flow. (Which probably says 'Unknown error').

**Comment by janmolemans** [comment]
Did you fill in the correct username (which is "User")?
