### ISSUE TITLE
Can't find integration in HACS

### ISSUE THREAD

**Issue by tamueller** [iMicknl/ha-sagemcom-fast#39]
I'm not able to install this integration via HACS, as I can't find it in the list there. Has this been "removed" from the HACS filter, or am I doing something wrong?

![image](https://user-images.githubusercontent.com/1902960/155879061-a62a7d18-cc5a-4c0c-840e-45040117521a.png)

**Comment by iMicknl** [comment]
It has never been added to the official HACS repository. You first need to add this repository, [as documented in the README](https://github.com/iMicknl/ha-sagemcom-fast#hacs).

**Comment by tamueller** [comment]
Ok, thanks for clarifying. I already read the README, but got confused by HACS and hat "adding integration" and "adding a repository" means. Would it be possible to change the readme from

"Add this repository to HACS," to
"Add this repository as a custom repository to HACS as described here (https://hacs.xyz/docs/faq/custom_repositories), "

In order to prevent newbies like me to get confused?

**Comment by iMicknl** [comment]
We can change that in the future, or you can do a pull request to make the change.

Thanks for your suggestion.
