### ISSUE TITLE
SAGEMCOM 5566 VPI / VCI edit

### ISSUE THREAD

**Issue by snawfel1983** [iMicknl/ha-sagemcom-fast#47]
Hi
I am looking to change the vpi/vci of the 5566 (bell HH3000) from 0/35 to 0/38 to be able to make it work with a different ADSL provider

Is this something that can be done ?

**Comment by iMicknl** [comment]
Sorry I have no clue what you ask. What do you want to achieve in Home Assistant?

**Comment by snawfel1983** [comment]
There is a setting in ADSL which is VPI = 0 and VCI = 35 pre-configured in BELL home hub 3000.

I would like to know is there a way to access config file or upload a custom firmware where i change the VCI to 38 value

Thank you

**Comment by iMicknl** [comment]
@snawfel1983 that would be out of scope for this Home Assistant integration unfortunately…

and unfortunate, I wouldn’t know where else to ask this…
