### ISSUE TITLE
Bbox F@st5688b seems not working

### ISSUE THREAD

**Issue by scalmaa** [iMicknl/ha-sagemcom-fast#48]
Hi.

I'm trying to connect to my bBox SagemCom F@st5688B. I'm using HA OS ans HACS module integration.

When I'm trying to connect with the user = admin and (my_password) with MD5 or SHA512 the connection is refused.

I don't known if it shoud be working ?

Thanks for your response

**Comment by M4D1NG3R** [comment]
Hey scalmaa,
Without a log, it would be pretty difficult for us to help you, so it would be an advantage if you could provide one.

**Comment by scalmaa** [comment]
Where can I find the logs. I'm looking for it but don't find it. Thanks for your help

**Comment by scalmaa** [comment]
I found nothing in the HA OS log.

**Comment by scalmaa** [comment]
I found this, I could be close to the problem, I don't know

Logger: asyncio
Source: /usr/local/lib/python3.9/asyncio/selector_events.py:911
First occurred: 19:37:29 (1 occurrences)
Last logged: 19:37:29

socket.send() raised exception.

**Comment by M4D1NG3R** [comment]
I'm sorry, but I can't really pinpoint the problem with that.

Do you know the basics of python?

If so, you could get a more detailed log with the quickstart script of the [sagemcom_api](https://github.com/iMicknl/python-sagemcom-api).

**Comment by scalmaa** [comment]
A little bit. Do I need to install the sagemcom_api manually ?
I installed the integration by HACS
Thanks

**Comment by M4D1NG3R** [comment]
One thing I forgot: Did you...


**Enable debug logging**
The [logger](https://www.home-assistant.io/integrations/logger/) integration lets you define the level of logging activities in Home Assistant. Turning on debug mode will show more information to help us understand your issues.


```
logger:
  default: critical
  logs:
    custom_components.sagemcom_fast: debug
```

**Comment by dridridu56** [comment]
@scalmaa Did you manage to connect to the bbox ? I try but I can't.


> I'm sorry, but I can't really pinpoint the problem with that.
> 
> Do you know the basics of python?
> 
> If so, you could get a more detailed log with the quickstart script of the [sagemcom_api](https://github.com/iMicknl/python-sagemcom-api).

I tried the API, and I got a message that sends me "0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://mabbox.bytel.fr')" with HOST = "192.168.1.254"

I've tried with HOST = "https://mabbox.bytel.fr" and obviously message "Cannot connect to host https:80 ssl:default [getaddrinfo failed]"
