### ISSUE TITLE
Sagemcom 5668w TMobile

### ISSUE THREAD

**Issue by southsideringo** [iMicknl/ha-sagemcom-fast#52]
Hi. I've managed to hunt down a bunch of api endpoints for this router.  But I'm still missing important things. Such as how to put it in bridge mode. So I'm most of the way ther I believe. 

It has the 192.168.12.1 gateway and then if I send curl or other REST api requests at like http://192.168.12.1/TMI/v1/network/configuration/get-ap -- I get back a pretty big json message thats easy to parse. If you want to add this machine to your collection, let me know.  Anyway the entire struggle has been trying to figure out the correct endpoints to try. Frustrating that these large corporations have chosen to release products that are essentially black boxes of mystery to most consumers.  Very frustrating. Have a good day.

**Comment by iMicknl** [comment]
@southsideringo does this integration work with your device? Looking at your URL, it seems to be a different API, hence the question.

**Comment by christophermichaelshaw** [comment]
The integration does not work, likely due to the different API
