### ISSUE TITLE
Reloading Issue Sagemcom F@st3896

### ISSUE THREAD

**Issue by fcardillo50** [iMicknl/ha-sagemcom-fast#53]
## Versions
| Key                                                     | Value |
|-----------------------------------------|-------|
| Home Assistant version                     |2022.11.5|
| Integration version                             |LATEST|
| Sagemcom F@st model                     |3896|
| Sagemcom F@st firmware (optional) |       |

## Description of the bug
Hi,

I want to let you know that this integration is awesome!! It works on the Sagemcom F@st3896. 

The only issue that I am having is that I need to manually reload the integration to get the updated device tracking information for devices such as mobile phones that leave my home. I've waited hours and I can see my device connected to my router. I'm not sure if I can do reload the integration through an automation or if you have the ability to do it in the integration. The refresh time is set to 10 seconds, but I don't get the updates in home assistant unless I manually reload.

## To Reproduce

1. Disconnect mobile device from Wi-Fi on the Sagemcom F@st3896.
2. Reconnect the Wi-Fi on the Sagemcom F@st3896.
3. Device tracking does not update.
4. Manually reload the integration.
5. Device tracking is now updated.

## Expected behavior
Automatic update to the device tracking information. 

[bug]

**Comment by iliDaedalus** [comment]
Same here.
Also if the device (eg. phone) is not in the network when the integration loads _(either by full system restart or by just integration reload)_, it doesn't track anymore when the device (eg. phone) connects back or either out again.
I am not sure, if it tracks and warns successfully when a **new** device connects to the WiFi.

**Comment by davej99** [comment]
I've got the same issue as iliDaedalus, all phones need to be logged in when server starts or integration is reloaded, or else the entity is unknown.
