### ISSUE TITLE
Investigate autodiscover via SSDP/DHCP

### ISSUE THREAD

**Issue by iMicknl** [iMicknl/ha-sagemcom-fast#6]
Working towards an official core integration, it would be great if we could discover Sagemcom F@st routers in a network.

In the past I came up with the following SSDP definition (not included in Config Flow), but I assume it could work with the new DHCP mode as well.

```json
"ssdp": [
    {
      "deviceType": "urn:schemas-wifialliance-org:device:WFADevice:1",
      "manufacturer": "Sagemcom Broadband SAS"
    },
    {
      "deviceType": "urn:schemas-upnp.org:device:InternetGatewayDevice:1",
      "manufacturer": "Sagemcom Broadband SAS"
    }
  ],
  "dhcp": [
    {
      "macaddress": "D8A756*"
    }
  ]
```

**Comment by iMicknl** [comment]
Looking at the Mac Addresses for the DHCP discovery, there are quite some: https://www.adminsub.net/mac-address-finder/sagemcom.


Mine starts with D8:A7:56, would be good if we can pinpoint which mac address reflect the F@st series.

**Comment by iMicknl** [comment]
@arunpoudel what are the first 6 numbers of your mac address? I wonder if all Sagemcom F@st devices share the same mac address vendor, or if they use multiple.

**Comment by arunpoudel** [comment]
Mine starts with EC:BE:DD

**Comment by geert36** [comment]
First 6 numbers of my mac adress: 8C:C5:B4.
