### ISSUE TITLE
Unable to add integration for KPN box 12b

### ISSUE THREAD

**Issue by Abhishek-tarun** [iMicknl/ha-sagemcom-fast#62]
I am trying to add the KPN box 12b. It's sagecom but it does not allow me to add the itegration, gives me an 'Invalid authentication' error.

**Comment by dejongmarten** [comment]
Use SHA512 and make sure you are logged out of de admin backend.

**Comment by roelvdgun** [comment]
I have a problem with the KPN box 12. It worked earlier, but since some time I got the following error and don't know what I have done wrong. Could somebody help me with this?

![image](https://github.com/iMicknl/ha-sagemcom-fast/assets/42893095/98e2e881-7c1d-4167-868a-f740264fa050)

**Comment by iMicknl** [comment]
@roelvdgun this is most likely related to a HA update. I haven't had time to really work on this integration for a long time, thus it is likely outdated.

**Comment by iMicknl** [comment]
Please update your integration and create a new issue if you still face issues.
