### ISSUE TITLE
Sagemcom f@st 5566 Virgin mobile: failed to set up

### ISSUE THREAD

**Issue by abidifethi** [iMicknl/ha-sagemcom-fast#63]
Can't get the sagemcom fast 5566 for virgin mobile working I can add it as integration with guest user and emty password  but it says failed to set up.

**Comment by iMicknl** [comment]
Please share logs.

**Comment by abidifethi** [comment]
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/sagemcom_fast/__init__.py:54
Integration: Sagemcom F@st (documentation, issues)
First occurred: 5:35:31 PM (2 occurrences)
Last logged: 5:40:20 PM

Error setting up entry 192.168.2.1 for sagemcom_fast
Error setting up entry 192.168.1.254 for sagemcom_fast
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sagemcom_fast/__init__.py", line 54, in async_setup_entry
    password = entry.data[CONF_PASSWORD]
               ~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'password'

**Comment by abidifethi** [comment]
setting done by changing user and password both to admin
