### ISSUE TITLE
It works for FAST3896 provided by Telecentro Argentina

### ISSUE THREAD

**Issue by arpena** [iMicknl/ha-sagemcom-fast#64]
Options:
User admin 
Pass <same as router admin page>
sha512
Uses SSL

**Comment by Zetor77** [comment]
This model working, branded by Finnish operator DNA. Login Works with sha512 with or without SSL. No sensors available tho.

**Comment by iMicknl** [comment]
@Zetor77 please create a new issue if you have a feature request for specific sensors.
