### ISSUE TITLE
Sagemcom F@st 5655V2 login - Failed to connect, please try again

### ISSUE THREAD

**Issue by veress1991** [iMicknl/ha-sagemcom-fast#65]
Hello,

I have a router Telekom - Sagemcom F@st 5655V2 AC. Theoretically the device is supported.
However when I try to login, I have got the following message "_Failed to connect, please try again_"
In the Host field I write the IP address, with this can be reach the router from browser - "192.168.1.1". 
I use the username and password, that is mentioned under the router.
The Encryption Method is MD5 I also tried with SHA512 but same issue.

Regards,
Gabor

**Comment by iMicknl** [comment]
@veress1991 sorry for the late reply. It will be very hard to debug this from distance. It is possible that your manufacturer changed the interface and API. 

At the moment I don't know how to help you unfortunately.
