### ISSUE TITLE
No entities found

### ISSUE THREAD

**Issue by raolss** [iMicknl/ha-sagemcom-fast#66]
## Versions

| Key                               | Value |
|-----------------------------------|-------|
| Home Assistant version            |  2023.9.1     |
| Integration version               |     latest  |
| Sagemcom F@st model               |  FAST3890V3_WIFIHUBC2_sw18.76.15.17w-6     |
| Sagemcom F@st firmware (optional) |    FAST3890V3_WIFIHUBC2_sw18.76.15.17w-6   |

## Describe the bug

No entities found, the device trackers are still there but unavailable 

## Expected behavior

Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by geert36** [comment]
Same problem here.

**Comment by raolss** [comment]
Restored to 2023.8.4 and it works

**Comment by raolss** [comment]
> Same problem here.

Have you upgraded and has that resolved the issue?

**Comment by raolss** [comment]
Updated HA and manually inserted your change. Works fine. New release?

**Comment by raolss** [comment]
@iMicknl any idea why HACS doesn't trigger an update although it indicates there is a new release?
