### ISSUE TITLE
Sagemcom 5359

### ISSUE THREAD

**Issue by raoulteeuwen** [iMicknl/ha-sagemcom-fast#70]
Hello.

As a user of a Sagemcom Fast5359 (which is sold/used in the Netherlands by KPN as 'Box 12') i tried your HACS component, and was able to get the config flow working. I used the admin account for it, so with a password, and sha512 as authentication method .

I for now only see 1 device, no other info.

**Comment by jvberlo** [comment]
Home-assistant.log does show more.

For every device a line like below.
11-15 16:09:40.574 ERROR (MainThread) [homeassistant.components.device_tracker] sagemcom_fast: Not adding entity with invalid device info: Invalid device info {'default_name': 'TIZEN', 'identifiers': {('sagemcom_fast', '00:FC:2D:FF:1F:B8')}, 'via_device': ('sagemcom_fast', '136b83181995e0d1b101cfe112f49919')} for 'sagemcom_fast' config entry: device info needs to either describe a device, link to existing device or provide extra information.

and then 

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 582, in _async_add_entity
    entity_name = entity.name
                  ^^^^^^^^^^^
  File "/config/custom_components/sagemcom_fast/device_tracker.py", line 99, in name
    or self.device.mac_address
       ^^^^^^^^^^^^^^^^^^^^^^^
```

I hope this helps to resolve.

@iMicknl  i  hope you can resolve this. This is from a new KPN Box 12 modem. If needed i can test it.

Greetings Jeroen

**Comment by SjoerdRk** [comment]
Same problem here, KPN BOX 12 (Sagemcom Fast5359), 

3 log messages:
`Error while setting up sagemcom_fast platform for device_tracker
18:51:42 – (ERROR) Device tracker
Error adding entities for domain device_tracker with platform sagemcom_fast
18:51:42 – (ERROR) Device tracker
sagemcom_fast: Not adding entity with invalid device info: Invalid device info {'default_name': 'NVR', 'identifiers': {('sagemcom_fast', 'asdfqwerty')}, 'via_device': ('sagemcom_fast', 'asfdasdfasdfasdf')} for 'sagemcom_fast' config entry: device info needs to either describe a device, link to existing device or provide extra information.
18:51:42 – (ERROR) Device tracker - message first occurred at 18:51:42 and shows up 13 times`

this is 3th one:
`Logger: homeassistant.components.device_tracker
Source: helpers/entity_platform.py:623


sagemcom_fast: Not adding entity with invalid device info: Invalid device info {'default_name': 'NVR', 'identifiers': {('sagemcom_fast', 'asdfqwerty')}, 'via_device': ('sagemcom_fast', 'asdfqwerty')} for 'sagemcom_fast' config entry: device info needs to either describe a device, link to existing device or provide extra information.
sagemcom_fast: Not adding entity with invalid device info: Invalid device info {'default_name': 'wiz_ff7f06', 'identifiers': {('sagemcom_fast', 'asdfqwerty')}, 'via_device': ('sagemcom_fast', 'asdfqwerty')} for 'sagemcom_fast' config entry: device info needs to either describe a device, link to existing device or provide extra information.

**Comment by iMicknl** [comment]
I haven't spend a lot of love on this integration in the last year(s). I would need to see if I can plan some time to fix it.

**Comment by iMicknl** [comment]
Could you please check-out the latest version and create a new issue if you still face issues? Happy to see how we can debug this.
