### ISSUE TITLE
Support for Fast 5866T

### ISSUE THREAD

**Issue by jam-hur** [iMicknl/ha-sagemcom-fast#71]
Hi there,

Thank you for your contribution.

I have the HACS add-on installed successfully but I'm unable to log in with various credentials and authentication types.

 Is there any support for Fast 5866T?

Many thanks.

`2023-10-09 14:30:07.660 ERROR (MainThread) [custom_components.sagemcom_fast.config_flow] <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>404 Not Found</title>
 </head>
 <body>
  <h1>404 Not Found</h1>
 </body>
</html>
Traceback (most recent call last):
  File "/config/custom_components/sagemcom_fast/config_flow.py", line 86, in async_step_user
    return await self.async_validate_input(user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sagemcom_fast/config_flow.py", line 69, in async_validate_input
    await client.login()
  File "/usr/local/lib/python3.11/site-packages/sagemcom_api/client.py", line 270, in login
    response = await self.__api_request_async([actions], True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sagemcom_api/client.py", line 200, in __api_request_async
    raise UnknownException(result)
sagemcom_api.exceptions.UnknownException: <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>404 Not Found</title>
 </head>
 <body>
  <h1>404 Not Found</h1>
 </body>
</html>`

**Comment by daniel-c-ctrl** [comment]
Seconded :)

logger: custom_components.sagemcom_fast.config_flow
Source: custom_components/sagemcom_fast/config_flow.py:87
Integration: Sagemcom F@st ([documentation](https://github.com/imicknl/ha-sagemcom-fast), [issues](https://github.com/imicknl/ha-sagemcom-fast/issues))
First occurred: 7:10:47 AM (1 occurrences)
Last logged: 7:10:47 AM

<?xml version="1.0" encoding="iso-8859-1"?> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> <head> <title>404 Not Found</title> </head> <body> <h1>404 Not Found</h1> </body> </html>
Traceback (most recent call last):
  File "/config/custom_components/sagemcom_fast/config_flow.py", line 87, in async_step_user
    return await self.async_validate_input(user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sagemcom_fast/config_flow.py", line 69, in async_validate_input
    await client.login()
  File "/usr/local/lib/python3.11/site-packages/sagemcom_api/client.py", line 271, in login
    response = await self.__api_request_async([actions], True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sagemcom_api/client.py", line 201, in __api_request_async
    raise UnknownException(result)
sagemcom_api.exceptions.UnknownException: <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>404 Not Found</title>
 </head>
 <body>
  <h1>404 Not Found</h1>
 </body>
</html>

**Comment by iMicknl** [comment]
I will need to work on a better error message here, but it seems your router is not supported and is using a different endpoint.

**Comment by daniel-c-ctrl** [comment]
No worries.
I've had a look at your python-sagemcom-api repository too, and that also doesn't seem to work with this modem.  Or at least I can't get it to work.
192.168.1.1: Gives 404 error

Having a look at some of your other posts, on the network tab I get this:
![image](https://github.com/iMicknl/ha-sagemcom-fast/assets/55867435/5be213a1-5955-482a-9ff2-8770355510ee)

And I _do_ have xhr type requests.
![image](https://github.com/iMicknl/ha-sagemcom-fast/assets/55867435/0736a679-7ce7-4d4e-8ac9-3bf0fc56f706)

Anything I can do to help (if you do want to support this) or can you point me in the right direction, and I might try to muddle my way through it?

**Comment by Tmbao** [comment]
I'm also using 5866T provided by TPG, it seems to have been built on a different firmware and therefore the API endpoints are different. As far as I can see:
 - `api/v1/login-params` generates a BBOX_ID but does not authenticate, it seems to me that BBOX_ID works like a session id
 - `api/v1/login` with the generated BBOX_ID in the cookie, username, jwt-like encrypted password makes the given BBOX_ID an authenticated session (unsure TTL tho)
 - below are some of the available APIs after authenticated
<img width="663" alt="image" src="https://github.com/iMicknl/ha-sagemcom-fast/assets/7766181/9aaa8131-0c9b-4a30-ba48-11ec511d9164">

I don't know how much this integration provides but it's probably great if we can somehow reuse the python library with minimal changes

**Comment by iMicknl** [comment]
@Tmbao nice find. Your API is totally different unfortunately, so that will require some more work I am afraid.
