### ISSUE TITLE
Integration does not work on recent HA versions

### ISSUE THREAD

**Issue by Fgreg881** [iMicknl/ha-sagemcom-fast#74]
## Versions

| Key                               | Value |
|-----------------------------------|-------|
| Home Assistant version            |   2023.11.3    |
| Integration version               |       |
| Sagemcom F@st model               |    5566   |
| Sagemcom F@st firmware (optional) |       |

## Describe the bug

Sagemcom Fast 5566 (Bell Home Hub 3000).
Admin account with password  and md5 authentication method.
Only see the device, no entities found.
No errors log on debug mode
With home assistant version 2023.8.4, the device could see over 40 entities.

## Expected behavior

Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by iMicknl** [comment]
Please try the latest version (0.2.10) and let me know if it doesn't work.

**Comment by Fgreg881** [comment]
Hello,
It works correctly with version 0.3.0.
I can see now the entities of the device.
Thank you very much, your work is greatly appreciated
Francois
________________________________
