### ISSUE TITLE
SagemcomFast5359_KPN

### ISSUE THREAD

**Issue by IZ3S1H** [iMicknl/ha-sagemcom-fast#75]
I have to enter credentials but also a **Host***.

What is the host? The IP address?

![image](https://github.com/iMicknl/ha-sagemcom-fast/assets/120579695/6f713e38-e282-45b1-b431-fe8588733adf)

**Comment by IZ3S1H** [comment]
The IP from the KPN box does not work.

**Comment by jvberlo** [comment]
I used the ip for my 5359 kpn box and it works

**Comment by iMicknl** [comment]
See https://github.com/iMicknl/ha-sagemcom-fast/issues/82 for the configuration details.

Host: https://mijnmodem.kpn/
Username: admin
Encryption Method: SHA512
SSL: True
SSL Verify: False 


Let me know if you still face issues, and I can reopen.
