### ISSUE TITLE
Sagemcom F@st 5360

### ISSUE THREAD

**Issue by sodfenrir** [iMicknl/ha-sagemcom-fast#76]
I've seen that the dev has no time / not the device to keep on going with this project.

If somebody has the knowledge to take over (i'de love to...), please think about adding support for the 5360 model.

I'm unable to log in, whatever the credential I'm testing.

Too bad, was really interesting! :)

**Comment by iMicknl** [comment]
@sodfenrir if you know Python, you can have a look at the underlying library. What is the error you get when logging in? (see your logs as well)

**Comment by sodfenrir** [comment]
Hi @iMicknl ! Thank you for your answer.

I wish I knew Python, but unfortunatly, that's not the case yet. 

My HA are empty regarding this problem and show nothing. The only message I receive is during the integration process, where I get "Failed to connect, please try again". 

I really wish I could help more, but learning Python is not in the top of my bucket list. It is on it, but not at the top...

**Comment by sodfenrir** [comment]
Oh, well, i got one. Not really sure it'll help, because I've made so many failed tries on loggin, so some were in https and other not. 
The problem is, other failures to login won't add anything to the logs, even in debug mode.

But got one anyways:



Cette erreur provient d'une intégration personnalisée

Logger: custom_components.sagemcom_fast.config_flow
Source: custom_components/sagemcom_fast/config_flow.py:86
Integration: Sagemcom F@st (documentation, issues)
First occurred: 17:56:19 (1 occurrences)
Last logged: 17:56:19

<html> <head><title>400 The plain HTTP request was sent to HTTPS port</title></head> <body> <center><h1>400 Bad Request</h1></center> <center>The plain HTTP request was sent to HTTPS port</center> <hr><center>nginx</center> </body> </html>
Traceback (most recent call last):
  File "/config/custom_components/sagemcom_fast/config_flow.py", line 86, in async_step_user
    return await self.async_validate_input(user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sagemcom_fast/config_flow.py", line 69, in async_validate_input
    await client.login()
  File "/usr/local/lib/python3.11/site-packages/sagemcom_api/client.py", line 270, in login
    response = await self.__api_request_async([actions], True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sagemcom_api/client.py", line 196, in __api_request_async
    raise BadRequestException(result)
sagemcom_api.exceptions.BadRequestException: <html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx</center>
</body>
</html>

**Comment by iMicknl** [comment]
Can you send a screenshot of what you put in the config flow? (the screen you get when you configure this configuration).

**Comment by sodfenrir** [comment]
![Sans titre](https://github.com/iMicknl/ha-sagemcom-fast/assets/151880733/186c6468-c559-4997-9bd8-01e861ea6afa)

Here you are. But I don't think we should focus on the HTTPS errors, I guess it only came because I've tried every credential I could. 

This means, including https://, http://, in the adresse, SSL ticked or not, SHA512...

You just pushed an update, didn't you? ;-) Well, now I get a "Failed to connect, please try again".

**Comment by iMicknl** [comment]
It is very hard to debug this from distance, because this would mean that the API is not there, or that it can't make a connection. 

Is there a way to open up the connection to you router via the public internet? (Enable external access).

**Comment by jsongerber** [comment]
Hi, I have this model too.
I also had an error connecting and got those logs:

```
2024-10-31 22:43:51.979 INFO (MainThread) [backoff] Backing off __post(...) for 0.3s (aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host 192.168.1.1:443 ssl:default [[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] ssl/tls alert handshake failure (_ssl.c:1000)])
2024-10-31 22:43:52.349 INFO (MainThread) [backoff] Backing off __post(...) for 1.0s (aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host 192.168.1.1:443 ssl:default [[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] ssl/tls alert handshake failure (_ssl.c:1000)])
2024-10-31 22:43:53.388 INFO (MainThread) [backoff] Backing off __post(...) for 1.4s (aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host 192.168.1.1:443 ssl:default [[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] ssl/tls alert handshake failure (_ssl.c:1000)])
2024-10-31 22:43:54.787 INFO (MainThread) [backoff] Backing off __post(...) for 7.4s (aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host 192.168.1.1:443 ssl:default [[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] ssl/tls alert handshake failure (_ssl.c:1000)])
2024-10-31 22:44:02.188 ERROR (MainThread) [backoff] Giving up __post(...) after 5 tries (aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host 192.168.1.1:443 ssl:default [[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] ssl/tls alert handshake failure (_ssl.c:1000)])
```

How can I help? I have some python knowledge but am a HA noob, thanks!

**Comment by iMicknl** [comment]
Did you try turning of SSL?

**Comment by jsongerber** [comment]
Thank you for your response, I tried to turn off ssl without success, I also tried to put other ssl settings and it finally worked with those settings:
Encryption: `EncryptionMethod.MD5`

SSL settings:
```python
ssl_context = ssl1.create_default_context()
ssl_context.check_hostname = False
ssl_context.verify_mode = ssl1.CERT_NONE
ssl_context.set_ciphers("DEFAULT:@SECLEVEL=1")
```

I think this belong to [your other repository](https://github.com/imicknl/python-sagemcom-api), but I don't really know how to integrate to this library without breaking anything.
I will gladly open a PR but I would appreciate you guiding me to the right direction, should I use an option for `SagemcomClient`, should I add this settings to auto try?

**Comment by iMicknl** [comment]
@jsongerber most likely your SSL problem is caused by another issue that we should have fixed in the underlying library, but which isn't part of ha-sagemcom-fast yet. Could you try if you can connect with the default settings on python-overkiz-api?

**Comment by jsongerber** [comment]
Yes, I think you meant the python-sagemcom-api. I opened [an issue there](https://github.com/iMicknl/python-sagemcom-api/issues/366).

**Comment by iMicknl** [comment]
@jsongerber can you try if 0.3.6 fixed your SSL issues? https://github.com/iMicknl/ha-sagemcom-fast/releases/tag/v0.3.6

**Comment by jsongerber** [comment]
Unfortunately no still the same problem

**Comment by iMicknl** [comment]
What do you get as an error when SSL is unchecked? Because your changes should not be required, this would mean that the Verify SSL feature is not working as expected..

Unfortunately I don't have time to dive into this the coming weeks.

**Comment by jsongerber** [comment]
This is the same handshake error as posted before, which seems to happen after a timeout.
The certificate on my router is a self signed one which is flagged as non secure by the browser, if that's revelant.
No worry if you don't have time, I'll fork and use my hacky solution for now.
If you want me to create a PR on the sagemcom api library feel free to answer my issue that I linked in my previous response.
Thanks
