### ISSUE TITLE
HACS not installing v0.2.9

### ISSUE THREAD

**Issue by thefreakquency** [iMicknl/ha-sagemcom-fast#77]
## Versions

| Key                               | Value |
|-----------------------------------|-------|
| Home Assistant version            |   2023.12.0    |
| Integration version               |    0.2.8   |
| Sagemcom F@st model               |    5689 (Bell HH4000)  |
| Sagemcom F@st firmware (optional) |   1.19.6    |

## Describe the bug

HACS does not provide latest release for installation. It install 0.2.8 which seems broken in newer HA versions. 

## To Reproduce

* Install as per https://github.com/iMicknl/ha-sagemcom-fast#hacs 

## Expected behavior
* Latest version installed

## Screenshots
![image](https://github.com/iMicknl/ha-sagemcom-fast/assets/25624251/26026fef-1384-4cc0-bab3-435758db718f)

## Additional context

[bug]

**Comment by iMicknl** [comment]
Should be fixed! Let me know if it still doesn't work for you.
