### ISSUE TITLE
Sagemcom Fast5670

### ISSUE THREAD

**Issue by vgroskin** [iMicknl/ha-sagemcom-fast#79]
The router connects, but does not see objects.
Fast5670_GPON
SGFg12000036

Logger: custom_components.sagemcom_fast
Source: helpers/update_coordinator.py:332
Integration: Sagemcom F@st (documentation, issues)
First occurred: 22:58:29 (1 occurrences)
Last logged: 22:58:29

Error fetching sagemcom_hosts data: Error communicating with API:

**Comment by iMicknl** [comment]
Please try the latest update, let me know if it isn't fixed and I will reopen this issue.

**Comment by vgroskin** [comment]
Everything is working. Thank you
