### ISSUE TITLE
Version 0.2.9 not released properly

### ISSUE THREAD

**Issue by arneroen** [iMicknl/ha-sagemcom-fast#81]
It appears version 0.2.9 has not been properly released.  There is a v0.2.9 tag https://github.com/iMicknl/ha-sagemcom-fast/releases/tag/v0.2.9

But looking at https://github.com/iMicknl/ha-sagemcom-fast/releases/, the last proper release appears to be 0.2.8. This would also explain why HACS flags the last available version as 0.2.8.

![image](https://github.com/iMicknl/ha-sagemcom-fast/assets/10383358/f76880d0-3dd3-47c7-b76d-893ff1001065)

**Comment by iMicknl** [comment]
Thanks for reporting, @arneroen! Does it work when you install master?

Looking at the v0.2.9 branch, it has the right version (0.2.9) in the manifest.json and the tag appears to be correct. I will have a look at this when I modernize this branch a bit.

**Comment by iMicknl** [comment]
Not sure what went wrong, but seems fixed now. Let me know if you still face issues, and we can reopen this issue.
