### ISSUE TITLE
KPN Sagecom Box 12

### ISSUE THREAD

**Issue by OldRon1977** [iMicknl/ha-sagemcom-fast#82]
Hello,
I have a Sagecom Router which is provided by KPN (Netherlands).
I am not sure which Route Model it is and the device info is also not very helpful to me.
Maybe anybody her can give me advice on how to connect to the router or it can be supported in the future.
Here are the infos I got from the device page:

![image](https://github.com/iMicknl/ha-sagemcom-fast/assets/73475830/f9897e9c-583d-4670-bb5c-dec70c4691c8)

If any other infos are needed, please let me know, I will try to provide them.

**Comment by geert36** [comment]
Hi @OldRon1977 the KPN Box 12 is already supported, you can use these settings:
![image](https://github.com/iMicknl/ha-sagemcom-fast/assets/77209691/af5b7e9f-de21-42e6-927c-44c3679495c1)
See also: https://github.com/iMicknl/ha-sagemcom-fast/issues/19

**Comment by OldRon1977** [comment]
Thanks a lot!
I tried many different variations for the login, but this one did the trick. 😁
