### ISSUE TITLE
Fast 5359 - KPN Box 12 - Reboot button not working

### ISSUE THREAD

**Issue by OldRon1977** [iMicknl/ha-sagemcom-fast#94]
## Versions

| Key                               | Value |
|-----------------------------------|-------|
| Home Assistant version            |   Core: 2024.1.2 | Supervisor: 2023.12.0 | Operating System: 11.3 | Frontend: 20240104.0    |
| Integration version               |    v0.3.1   |
| Sagemcom F@st model               |   5359    |
| Sagemcom F@st firmware (optional) |  SGEJ1000060E     |

## Describe the bug

The Button "Reboot" has no function. 

## To Reproduce

1. Go to 'Settings --> Devices --> Sagecom --> Devices --> Segemcom F5359'
2. Click on 'Reboot'
3. See error

## Expected behavior

I expect the router to reboot.

## Screenshots

![image](https://github.com/iMicknl/ha-sagemcom-fast/assets/73475830/1da839e3-f626-400c-ac75-9ad44b7bf499)

## Additional context

If more or different infos are needed, tell me what, and I will try to provide the infos.

[bug]

**Comment by iMicknl** [comment]
Does the reboot button work for you? It seems here that the reboot button works, but the response message is empty, which causes an error. I will work on fixing this.

**Comment by OldRon1977** [comment]
Hello,
the button does not work.
I also checked the modem logs, to see if there is any error, but no.
The modem logs show that every few seconds a login/logoff is successfully performed which should be the HA integration.
But no reboot is performed.

**Comment by geert36** [comment]
Same issue here, get a notification "Kan service button/press niet aanroepen. List index out of range"
![Screenshot_20240115_215733_Home Assistant](https://github.com/iMicknl/ha-sagemcom-fast/assets/77209691/d4d7d5c9-733a-4ff0-9c2f-6f12624a0753)
Also nothing in the log.

**Comment by OldRon1977** [comment]
Hello,
the issue is still there. I updated to the latest HA version, and still the reboot does not work.

Regards...

**Comment by iMicknl** [comment]
@OldRon1977 should be fixed in latest update!

**Comment by OldRon1977** [comment]
Yes :)
It is working. Thanks!
