### ISSUE TITLE
Wrong home/away status of devices

### ISSUE THREAD

**Issue by geert36** [iMicknl/ha-sagemcom-fast#97]
## Versions

| Key                               | Value |
|-----------------------------------|-------|
| Home Assistant version            |    Core: 2024.1.2   |
| Integration version               |   v0.3.1   |
| Sagemcom F@st model               |    5359  |
| Sagemcom F@st firmware (optional) |  SGEJ1000060E     |

## Describe the bug

Wrong home/away status of devices. For example, the integration indicates that my phone is home, while this is not the case.

## Expected behavior

Device status is 'not_home'.

## Additional context

[bug]

**Comment by iMicknl** [comment]
@geert36 did you check on your router page if it is listed as device there? Do you see any errors in the log?

**Comment by geert36** [comment]
Yes, it was listed on the router page without an IP. The KPN Thuis app is displaying the correct status.
