### ISSUE TITLE
Add support for devices with additional GUI_PASSWORD_SALT (e.g. Sagemcom 5670)

### ISSUE THREAD

**Issue by MiroG225** [iMicknl/ha-sagemcom-fast#98]
[https://drinia.tech/products/gpon/gpon-ont/sagemcom-gpon-ont/sagemcom-fst-5670/](url)

**Comment by eytanbiala** [comment]
Also can't get it to work with the 5670

Just says invalid authentication

**Comment by MiroG225** [comment]
> Have you tried it?

Sorry for late reply. Yes I did, and doesn't work.

**Comment by MiroG225** [comment]
There is no new version of integration since my first comment. So yes, teh issue is still present.
My HA and all integrations are always up to date.

**Comment by eytanbiala** [comment]
Issue is still present

**Comment by MiroG225** [comment]
Yep, still the same

🫤

**Comment by MiroG225** [comment]
It's probably problem of authentication. This is what Gemini AI told me:

I couldn't find specific information about Sagemcom 5670 using MD5 or SHA512 authentication.

However, based on my knowledge of router security practices, it's more likely that the Sagemcom 5670 uses a more secure hashing algorithm like SHA-256 or even SHA-3 for password authentication instead of MD5.

**Comment by eytanbiala** [comment]
Still present

**Comment by h00t2y** [comment]
One more vote for 5670 support please
Tried both encryption methods
Invalid authentication

**Comment by eytanbiala** [comment]
Still present

**Comment by iMicknl** [comment]
Most likely this can't be solved. I am thinking about adding a way to verify if the right endpoint is available on the router.. These things are hard to debug without access to the router itself.

**Comment by MiroG225** [comment]
Still present

**Comment by johnnyaug** [comment]
Would love to see this resolved :pray:

**Comment by iMicknl** [comment]
@johnnyaug lol, good find! Where did you find that they add this Salt?

**Comment by johnnyaug** [comment]
I unminified the JavaScript in the debug console and checked out what it was doing 😀

**Comment by iMicknl** [comment]
@johnnyaug if you would be willing to briefly document how you do this; we can see if we can add this to instructions in this repo (or the python-sagemcom-api), so that users can try to debug these kind of issues themselves as well. It seems the Sagemcom API comes in many different variants..

**Comment by johnnyaug** [comment]
Sure, I'll make sure today that I can close the loop and use it with the HA integration. Then I'll add it to the compatibility table in both repos.

**Comment by h00t2y** [comment]
[sagemcom5670valuestree.txt](https://github.com/user-attachments/files/16561127/sagemcom5670valuestree.txt)
I can login without Salt123.
However i can"t get device info nor anything else.

My test sagem.py:

import asyncio
from sagemcom_api.client import SagemcomClient
from sagemcom_api.enums import EncryptionMethod
from sagemcom_api.exceptions import NonWritableParameterException
HOST = "192.168.1.1"
USERNAME = ""
PASSWORD = ""
ENCRYPTION_METHOD = EncryptionMethod.SHA512
async def main() -> None:
    await asyncio.sleep(2)
    async with SagemcomClient(HOST, USERNAME, PASSWORD, ENCRYPTION_METHOD) as c>
        try:
            await client.login()
        except Exception as exception:  # pylint: disable=broad-except
            print(exception)
            return

        custom_command_output = await client.get_value_by_xpath("Device/DeviceInfo")
        print(custom_command_output)
#        device_info = await client.get_device_info()
#        print(f"{device_info.id} {device_info.model_name}")
asyncio.run(main())

Error:

$ python3 sagem.py
Traceback (most recent call last):
  File "/home/pi/sagem.py", line 64, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pi/sagem.py", line 32, in main
    custom_command_output = await client.get_value_by_xpath("Device/DeviceInfo")
  File "/home/pi/.local/lib/python3.9/site-packages/sagemcom_api/client.py", line 310, in get_value_by_xpath
    response = await self.__api_request_async([actions], False)
  File "/home/pi/.local/lib/python3.9/site-packages/sagemcom_api/client.py", line 192, in __api_request_async
    async with self.session.post(
  File "/home/pi/.local/lib/python3.9/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
  File "/home/pi/.local/lib/python3.9/site-packages/aiohttp/client.py", line 605, in _request
    await resp.start(conn)
  File "/home/pi/.local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 966, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/home/pi/.local/lib/python3.9/site-packages/aiohttp/streams.py", line 622, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

I can see from the router's log that login was succesfull. 
Please find attached file with the logs of $.xmo.getValuesTree("Device/DeviceInfo")  $.xmo.getValuesTree("*")  $.xmo.getValuesTree("*/*") and $.xmo.getValuesTree("*/*/*")

**Comment by iMicknl** [comment]
@h00t2y please create a seperate issue with all details and I will have a look.

@johnnyaug I added a function `get_encryption_method`, which I might extend eventually to retry all (known) SALT options. Or maybe even better, refactor the feature to pull the `/2.0/gui/js/gui-core.js` and parse the salt and encoding strings. The only issue here is that it might be at a different url, for example my router puts them at `/2.0`.

**Comment by eytanbiala** [comment]
Still present

**Comment by iMicknl** [comment]
@eytanbiala have you tried the suggest workaround?

> 🎉🎉 Good news - there is a workaround: to use 5670, add :Salt123 to your password when setting up the integration. So if your password is blabla, put blabla:Salt123 as the password. Use SHA512 encryption.

**Comment by MiroG225** [comment]
Adding :Salt123 doesn't work for me. Although I'm not sure what do you mean "Use SHA512 encryption". Could you explain pls? Also, should I use ssl and verify ssl? 
Thx.
